// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QLck-VoCj8cji1ok6Qd9Xw2_6fPtawE',
    appId: '1:569339522559:web:7597fc0908ec61bd580bca',
    messagingSenderId: '569339522559',
    projectId: 'athlete-app-5603b',
    authDomain: 'athlete-app-5603b.firebaseapp.com',
    databaseURL: 'https://athlete-app-5603b-default-rtdb.firebaseio.com',
    storageBucket: 'athlete-app-5603b.firebasestorage.app',
    measurementId: 'G-1QVM7J6NG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LKvlJpf0ZQNKBnbuG2ymmL1BDpcyPGQ',
    appId: '1:569339522559:android:559f2992cd5dc5a6580bca',
    messagingSenderId: '569339522559',
    projectId: 'athlete-app-5603b',
    databaseURL: 'https://athlete-app-5603b-default-rtdb.firebaseio.com',
    storageBucket: 'athlete-app-5603b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmJBKPdSZsJnmiXMWc5YeMurrR0KN72Mk',
    appId: '1:569339522559:ios:1d2e9d8fec226d36580bca',
    messagingSenderId: '569339522559',
    projectId: 'athlete-app-5603b',
    databaseURL: 'https://athlete-app-5603b-default-rtdb.firebaseio.com',
    storageBucket: 'athlete-app-5603b.firebasestorage.app',
    iosBundleId: 'com.example.athleteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmJBKPdSZsJnmiXMWc5YeMurrR0KN72Mk',
    appId: '1:569339522559:ios:1d2e9d8fec226d36580bca',
    messagingSenderId: '569339522559',
    projectId: 'athlete-app-5603b',
    databaseURL: 'https://athlete-app-5603b-default-rtdb.firebaseio.com',
    storageBucket: 'athlete-app-5603b.firebasestorage.app',
    iosBundleId: 'com.example.athleteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QLck-VoCj8cji1ok6Qd9Xw2_6fPtawE',
    appId: '1:569339522559:web:6c2feee5823411cf580bca',
    messagingSenderId: '569339522559',
    projectId: 'athlete-app-5603b',
    authDomain: 'athlete-app-5603b.firebaseapp.com',
    databaseURL: 'https://athlete-app-5603b-default-rtdb.firebaseio.com',
    storageBucket: 'athlete-app-5603b.firebasestorage.app',
    measurementId: 'G-6B7WVMRKPS',
  );
}
